ci/cd

diff --git a/Vocaloid/Jenkinsfile b/Vocaloid/Jenkinsfile
--- a/Vocaloid/Jenkinsfile
+++ b/Vocaloid/Jenkinsfile
@@ -1,75 +1,67 @@
 pipeline {
     agent {
-        docker { image 'mcr.microsoft.com/playwright:v1.46.0-jammy' }
+        docker { image 'mcr.microsoft.com/playwright:v1.47.2-jammy' }
     }
-
     environment {
-        GITHUB_URL = 'https://github.com/DuyThanhLieu/Automation-testing.git'
         REPO_NAME = 'Vocaloid'
         FILE_SH = 'Vocaloid_Auto.sh'
         FILE_BAT = 'Vocaloid_Auto.bat'
-        COMMAND = 'npx playwright test BS_Actions.spec.js --reporter=line --workers=1'
         SERVER_PATH = "Automation-testing/${REPO_NAME}"
+        SERVER_PROJECT = "Automation-testing"
         BRANCH_NAME = 'main'
+        JENKINS_CREDENTIALS_ID = '5c7bd325-a531-4236-8534-102e45de69e7'
+        chatId = '-1002308985537'
+        botToken = '8085219018:AAHSTNao6k9OucZc15LQ476N-039N8NR7WI'
     }
-
     triggers {
-        cron('0 1 * * *') // Chạy lúc 1:00 AM hàng ngày
+        cron('0 1 * * *')
     }
 
     stages {
         stage('CI: Checkout Code') {
             steps {
                 script {
-                    echo "Cloning repository from ${GITHUB_URL}"
-                    sh "git clone -b ${env.BRANCH_NAME} ${env.GITHUB_URL} ${env.SERVER_PATH}"
-
-                    echo "Setting up repository path..."
-                    env.REPO_PATH = "${env.SERVER_PATH}"
-
-                    echo "Current working directory:"
-                    sh 'pwd'
-
-                    echo "Listing contents of ${env.REPO_PATH}:"
-                    sh "ls -la ${env.REPO_PATH}"
-
-                    echo "Checking if Data directory exists..."
-                    sh """
-                        if [ -d "${env.REPO_PATH}/Data" ]; then
-                            echo "Data directory found."
-                        else
-                            echo "Data directory not found."
-                        fi
-                    """
+                    sh "git fetch origin ${BRANCH_NAME}"
+                    def changes = sh(script: "git diff --name-only origin/${BRANCH_NAME} ${BRANCH_NAME} || echo 'No changes detected'", returnStdout: true).trim()
+                    if (changes) {
+                        echo "Changes detected. Checking out code..."
+                        withCredentials([usernamePassword(credentialsId: "${JENKINS_CREDENTIALS_ID}", usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')]) {
+                            git branch: "${BRANCH_NAME}",
+                                credentialsId: "${JENKINS_CREDENTIALS_ID}",
+                                url: "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/DuyThanhLieu/Automation-testing.git"
+                        }
+                    } else {
+                        echo "No changes detected. Skipping checkout."
+                    }
+                    env.REPO_PATH = sh(script: "find . -type d -name '${REPO_NAME}'", returnStdout: true).trim()
+                    if (!env.REPO_PATH) {
+                        error "Repository folder ${REPO_NAME} not found."
+                    }
                 }
+                sh """
+                    cd ${env.REPO_PATH}
+                    chmod +x ${FILE_SH}
+                """
             }
         }
 
         stage('Setup Dependencies') {
             steps {
-                echo 'Setting up dependencies'
                 script {
                     sh """
                         cd ${env.REPO_PATH}
-                        
                         if [ -d "node_modules" ]; then
-                            echo "node_modules already exists. Checking Playwright version..."
-                            chmod +x node_modules/.bin/playwright
-
+                            echo "node_modules exists. Checking Playwright..."
                             if npx playwright --version; then
-                                echo "Playwright is already installed. Skipping installation."
+                                echo "Playwright installed. Skipping."
                             else
-                                echo "Playwright is not installed. Installing..."
                                 rm -rf node_modules package-lock.json
                                 npm install
                                 npx playwright install
-                                npm install @playwright/test@latest
                             fi
                         else
-                            echo "node_modules does not exist. Installing dependencies..."
                             npm install
                             npx playwright install
-                            npm install @playwright/test@latest
                         fi
                     """
                 }
@@ -78,60 +70,72 @@ pipeline {
 
         stage('CD: Run Tests') {
             steps {
-                echo 'Starting Tests'
                 script {
-                    try {
+                    if (isUnix()) {
                         sh """
                             cd ${env.REPO_PATH}
-                            ${env.COMMAND}
+                            chmod +x ${FILE_SH}
+                            ./${FILE_SH}
                         """
-                    } catch (Exception e) {
-                        echo "Test execution failed: ${e.getMessage()}"
-                        currentBuild.result = 'FAILURE'
+                    } else {
+                        bat """
+                            cd ${env.REPO_PATH}
+                            ${FILE_BAT}
+                        """
                     }
                 }
-                echo "Tests executed"
             }
         }
 
         stage('Archive Test Results') {
             steps {
                 archiveArtifacts artifacts: '**/playwright-report/**/*', allowEmptyArchive: true
-                echo 'Test results archived.'
             }
         }
     }
 
     post {
-        always {
-            script {
-                echo "Cleaning up temporary files..."
-                if (isUnix()) {
-                    sh """
-                        if [ -d "${SERVER_PATH}/temp" ]; then
-                            rm -rf ${SERVER_PATH}/temp/*
-                        else
-                            echo "Temporary folder does not exist."
-                        fi
-                    """
-                } else {
-                    bat """
-                        if exist ${SERVER_PATH}\\temp\\* del /Q ${SERVER_PATH}\\temp\\*
-                    """
-                }
-            }
-        }
-
         success {
             script {
-                echo "✅ All test cases passed successfully!"
+                sendBuildStatusMessage("✅ Status: ${currentBuild.currentResult}")
+                cleanTemporaryFolder()
             }
         }
-
         failure {
             script {
-                echo "❌ Some test cases failed. Check the logs."
+                sendBuildStatusMessage("❌ Status: ${currentBuild.currentResult}")
+                cleanTemporaryFolder()
             }
         }
     }
+}
+
+def cleanTemporaryFolder() {
+    script {
+        def pathsToCheck = [
+            "${env.REPO_PATH}/package-lock.json",
+            "${env.REPO_PATH}/playwright-report",
+            "${env.REPO_PATH}/Results",
+            "${env.REPO_PATH}/test-results"
+        ]
+        pathsToCheck.each { path -> sh "rm -rf ${path} || true" }
+    }
+}
+
+def sendBuildStatusMessage(statusBuild) {
+    TimeZone timeZone = TimeZone.getTimeZone('GMT+7')
+    def currentDate = new Date().format("dd-MM-yyyy", timeZone)
+    def currentTime = new Date().format("HH:mm:ss", timeZone)
+    def message = """
+    🌟 ${statusBuild} 🌟
+    📁 Repository: ${env.REPO_NAME}
+    📅 Date: ${currentDate}
+    🕒 Time: ${currentTime}
+    🔗 Jenkins Server: ${env.BUILD_URL}
+    """
+    sendMessageToTelegram(message)
+}
+
+def sendMessageToTelegram(message) {
+    sh "curl -s -X POST https://api.telegram.org/bot${botToken}/sendMessage -d chat_id=${chatId} -d text='${message}'"
 }
