update cicd new tongram

diff --git a/Tongram/Jenkinsfile b/Tongram/Jenkinsfile
--- a/Tongram/Jenkinsfile
+++ b/Tongram/Jenkinsfile
@@ -1,66 +1,111 @@
 pipeline {
     agent {
-        docker { image 'mcr.microsoft.com/playwright:v1.46.0-jammy' }
+        docker { image 'mcr.microsoft.com/playwright:v1.47.2-jammy' }
     }
-    environment {
-        GITHUB_URL = 'https://github.com/DuyThanhLieu/Automation-testing.git'
+environment {
         REPO_NAME = 'Tongram'
         FILE_SH = 'TG_Auto.sh'
         FILE_BAT = 'TG_Auto.bat'
-        COMMAND = 'npx playwright test BS_Actions.spec.js --reporter=line --workers=1'
-        SERVER_PATH = "Automation-testing/${REPO_NAME}"
+         SERVER_PATH = "Automation-testing/${REPO_NAME}"
+        SERVER_PROJECT = "automation-testing"
         BRANCH_NAME = 'main'
+        JENKINS_CREDENTIALS_ID = '5c7bd325-a531-4236-8534-102e45de69e7'
+        chatId = '-1002308985537'
+        botToken = '808521`9018:AAHSTNao6k9OucZc15LQ476N-039N8NR7WI'
+        RESULTS_FILE = "${env.REPO_PATH}/Results/test_results.json" 
     }
     triggers {
         cron('0 1 * * *')
     }
+    
     stages {
         stage('CI: Checkout Code') {
             steps {
-                git branch: "${BRANCH_NAME}", url: "${GITHUB_URL}"
-                echo "Code checked out from ${BRANCH_NAME}"
-                echo 'Current working directory:'
-                sh 'pwd'
-                echo "Finding ${REPO_NAME} directory:"
                 script {
-                    def repoPath = sh(script: "find . -type d -name '${REPO_NAME}'", returnStdout: true).trim()
-                    echo "Found ${REPO_NAME} at: ${repoPath}"
-                    env.REPO_PATH = repoPath
+                    def changes = sh(script: "git diff --name-only origin/${BRANCH_NAME}..${BRANCH_NAME}", returnStdout: true).trim()
+                    if (changes) {
+                        echo "Changes detected. Checking out code..."
+                        withCredentials([usernamePassword(credentialsId: "${JENKINS_CREDENTIALS_ID}", usernameVariable: 'GITHUB_USER', passwordVariable: 'GITHUB_TOKEN')]) {
+                            git branch: "${BRANCH_NAME}",
+                                credentialsId: "${JENKINS_CREDENTIALS_ID}",
+                                url: "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/DuyThanhLieu/Automation-testing.git" // nhớ phải thêm .git
+                        }
+                        echo "Code checked out from ${BRANCH_NAME}"
+                    } else {
+                        echo "No changes detected. Skipping checkout."
+                    }
+
+                    env.REPO_PATH = sh(script: "find . -type d -name '${REPO_NAME}'", returnStdout: true).trim()
+                    if (env.REPO_PATH) {
+                        echo "Found ${REPO_NAME} at: ${env.REPO_PATH}"
+                    } else {
+                        error "Repository directory ${REPO_NAME} not found."
+                    }
                 }
-                echo "Changing directory to ${REPO_NAME} and listing contents:"
                 sh """
                     cd ${env.REPO_PATH}
                     pwd
                     ls -la
                 """
-                echo "Checking if Data directory exists in ${REPO_PATH}:"
-                sh "ls -la ${env.REPO_PATH}/Data"
             }
         }
+
         stage('Setup Dependencies') {
             steps {
                 echo 'Setting up dependencies'
                 script {
                     sh """
                         cd ${env.REPO_PATH}
-                        rm -rf node_modules package-lock.json
-                        npm install
-                        npx playwright install
-                        npm install @playwright/test@latest
+
+                        if [ -d "node_modules" ]; then
+                            echo "node_modules already exists. Checking Playwright version..."
+                            chmod +x node_modules/.bin/playwright
+
+                            if npx playwright --version; then
+                                echo "Playwright is already installed. Skipping installation."
+                            else
+                                echo "Playwright is not installed. Installing..."
+                                rm -rf node_modules package-lock.json
+                                npm install
+                                npx playwright install
+                                npm install @playwright/test@latest
+                            fi
+                        else
+                            echo "node_modules does not exist. Installing dependencies..."
+                            npm install
+                            npx playwright install
+                            npm install @playwright/test@latest
+                        fi
                     """
                 }
             }
         }
-        stage('Verify Playwright Installation') {
-            steps {
-                echo 'Verifying Playwright Installation'
-                script {
-                    sh 'node -v'  
-                    sh 'npm -v' 
-                    sh 'npx playwright --version'  
-                }
-            }
-        }
+        // stage('Setup Dependencies') {
+        //     steps {
+        //         echo 'Setting up dependencies'
+        //         script {
+        //             sh """
+        //                 cd ${env.REPO_PATH}
+
+        //                 if [ ! -d "node_modules" ]; then
+        //                     echo "node_modules does not exist. Installing dependencies..."
+        //                     chmod +x node_modules/.bin/playwright
+        //                     npm install
+        //                 fi
+                        
+        //                 if ! npx playwright --version; then
+        //                     echo "Playwright is not installed. Installing Playwright and browsers..."
+        //                     rm -rf node_modules package-lock.json
+        //                     npx playwright install
+        //                     npm install @playwright/test@latest
+        //                 else
+        //                     echo "Playwright is already installed. Skipping installation."
+        //                 fi
+        //             """
+        //         }
+        //     }
+        // }
+
         stage('CD: Run Tests') {
             steps {
                 echo 'Starting Tests'
@@ -68,55 +113,122 @@ pipeline {
                     if (isUnix()) {
                         sh """
                             cd ${env.REPO_PATH}
-                            ${COMMAND}
+                            chmod +x ${FILE_SH} 
+                            ./${FILE_SH}
                         """
                     } else {
                         bat """
                             cd ${env.REPO_PATH}
-                            ${COMMAND}
+                            ${FILE_BAT}
                         """
                     }
                 }
                 echo "Tests executed"
             }
         }
+
         stage('Archive Test Results') {
             steps {
                 archiveArtifacts artifacts: '**/playwright-report/**/*', allowEmptyArchive: true
-echo 'Test results archived.'
+                echo 'Test results archived.'
             }
         }
     }
+
     post {
         success {
             script {
-                def status = currentBuild.result ?: 'SUCCESS'
-                echo "All test cases passed. Build status: ${status}"
-                if (isUnix()) {
-                    if (fileExists("${SERVER_PATH}/temp")) {
-                        sh "rm -rf ${SERVER_PATH}/temp/*"
-                    } else {
-                        echo "Temporary folder does not exist."
-                    }
-                } else {
-                    bat "if exist ${SERVER_PATH}\\temp\\* del /Q ${SERVER_PATH}\\temp\\*"
-                }
+                sendBuildStatusMessage("✅ Status: ${currentBuild.currentResult}")
+                cleanTemporaryFolder()
             }
         }
+
         failure {
             script {
-                def status = currentBuild.result ?: 'FAILURE'
-                echo "Some test cases failed. Build status: ${status}"
-                if (isUnix()) {
-                    if (fileExists("${SERVER_PATH}/temp")) {
-                        sh "rm -rf ${SERVER_PATH}/temp/*"
-                    } else {
-                        echo "Temporary folder does not exist."
-                    }
-                } else {
-                    bat "if exist ${SERVER_PATH}\\temp\\* del /Q ${SERVER_PATH}\\temp\\*"
-                }
+                sendBuildStatusMessage("❌ Status: ${currentBuild.currentResult}")
+                cleanTemporaryFolder()
             }
         }
     }
+}
+
+def cleanTemporaryFolder() {
+    script {
+        echo 'Cleaning up temporary files and directories...'
+        def pathsToCheck = [
+            "${env.REPO_PATH}/package-lock.json",
+            "${env.REPO_PATH}/playwright-report",
+            "${env.REPO_PATH}/Results",
+            "${env.REPO_PATH}/test-results",
+            "${env.REPO_PATH}/temp",
+            "${env.REPO_PATH}/logs"
+        ]
+        if (isUnix()) {
+            pathsToCheck.each { path ->
+                sh "if [ -e '${path}' ]; then echo '${path} exists'; fi"
+            }
+
+            sh """
+                rm -rf ${env.REPO_PATH}/package-lock.json 
+                rm -rf ${env.REPO_PATH}/playwright-report 
+                rm -rf ${env.REPO_PATH}/Results 
+                rm -rf ${env.REPO_PATH}/test-results 
+                rm -rf ${env.REPO_PATH}/temp/*
+                rm -rf ${env.REPO_PATH}/logs/*        
+                find ${env.REPO_PATH} -name '*.log' -delete  
+            """
+        } else {
+            pathsToCheck.each { path ->
+                def winPath = path.replace("/", "\\")
+                bat "if exist '${winPath}' (echo '${winPath} exists')"
+            }
+
+            bat """
+                del /Q ${env.REPO_PATH}\\package-lock.json 
+                rmdir /s /q ${env.REPO_PATH}\\playwright-report 
+                rmdir /s /q ${env.REPO_PATH}\\Results 
+                rmdir /s /q ${env.REPO_PATH}\\test-results 
+                del /Q ${env.REPO_PATH}\\temp\\* 
+                del /Q ${env.REPO_PATH}\\logs\\*           
+                del /Q ${env.REPO_PATH}\\*.log              
+            """
+        }
+    }
+}
+
+
+
+def sendBuildStatusMessage(statusBuild) {
+    TimeZone timeZone = TimeZone.getTimeZone('GMT+7')
+    def currentDate = new Date().format("dd-MM-yyyy", timeZone)
+    def currentTime = new Date().format("HH:mm:ss", timeZone)
+    def durationMillis = currentBuild.duration ?: 0
+    def minutes = (durationMillis / 60000).toInteger()  
+    def seconds = ((durationMillis % 60000) / 1000).toInteger()  
+
+    def commitId = env.GIT_COMMIT ?: 'N/A'
+    def branchName = env.GIT_BRANCH ?: 'N/A'
+    
+    def message = """
+    🌟🌟 ${statusBuild} 🌟🌟
+    ══════════════════════ 
+    📁 Repository: ${env.REPO_NAME}           
+    📅 Date: ${currentDate} 
+    🕒 Time: ${currentTime}                                  
+    ⏳ Duration: ${minutes} min ${seconds} sec  
+    ══════════════════════
+    🌿 Branch: ${branchName}       
+    🏷️ Commit ID: ${commitId}       
+    🔗 Jenkins Server: ${env.BUILD_URL}       
+    ══════════════════════
+    🔗 Thank you for your attention! 🚀
+    """
+    
+    sendMessageToTelegram(message)
+}
+
+
+
+def sendMessageToTelegram(message) {
+    sh "curl -s -X POST https://api.telegram.org/bot${botToken}/sendMessage -d chat_id=${chatId} -d text='${message}'"
 }
